// src/shared/widgets/base-button.vue
<script setup lang="ts">
/**
 * BaseButton — botão único do Design System (§8.2). Nenhuma tela monta botão
 * "na mão". Variantes mapeiam a intenção:
 *
 * - `primary`  — ação que inicia algo (Novo, Salvar, Entrar). Dourado.
 * - `danger`   — ação destrutiva (Excluir).
 * - `neutral`  — secundário/Cancelar. Borda discreta.
 * - `icon`     — botão-ícone quadrado (toolbar, header de diálogo).
 *
 * Altura mínima 40px (toque). Loading mostra spinner sem trocar a largura.
 */
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    variant?: 'primary' | 'danger' | 'neutral' | 'icon'
    type?: 'button' | 'submit'
    label?: string
    icon?: string
    iconRight?: string
    loading?: boolean
    disabled?: boolean
    block?: boolean
    size?: 'sm' | 'md'
  }>(),
  { variant: 'primary', type: 'button', size: 'md' },
)

const isIconOnly = computed(() => props.variant === 'icon')

const base =
  'ds-focus-ring inline-flex items-center justify-center gap-2 font-semibold ' +
  'transition-colors duration-[var(--duration-fast)] disabled:cursor-not-allowed disabled:opacity-40 ' +
  'whitespace-nowrap select-none'

const sizing = computed(() => {
  if (isIconOnly.value) return 'h-10 w-10 rounded-field text-base'
  const h = props.size === 'sm' ? 'h-9 px-3 text-sm' : 'h-10 px-4 text-sm'
  return `${h} rounded-field ${props.block ? 'w-full' : ''}`
})

const variantClass = computed(() => {
  switch (props.variant) {
    case 'danger':
      return 'bg-danger text-white hover:bg-danger/90'
    case 'neutral':
      return 'border border-line bg-surface-1 text-content-soft hover:bg-surface-2 hover:text-content'
    case 'icon':
      return 'text-content-muted hover:bg-surface-2 hover:text-content'
    case 'primary':
    default:
      return 'bg-accent text-on-accent hover:bg-accent-hover'
  }
})
</script>

<template>
  <button
    :type="type"
    :disabled="disabled || loading"
    :class="[base, sizing, variantClass]"
  >
    <i v-if="loading" class="pi pi-spinner animate-spin" aria-hidden="true"></i>
    <i v-else-if="icon" :class="['pi', icon]" aria-hidden="true"></i>
    <span v-if="label && !isIconOnly">{{ label }}</span>
    <slot v-if="!isIconOnly" />
    <i v-if="iconRight && !loading && !isIconOnly" :class="['pi', iconRight]" aria-hidden="true"></i>
  </button>
</template>

// src/shared/widgets/base-button.tsx
// Scope: [S] shared-project   Reuse: [P] package-candidate (@noturno/ui)
//
// Botão base do Design System. Variantes seguem a paleta Noturno. Encapsula
// estado de loading (spinner próprio em CSS) e acessibilidade básica.

"use client";

import type { ButtonHTMLAttributes, ReactNode } from "react";

type Variant = "primary" | "ghost";

type BaseButtonProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  variant?: Variant;
  loading?: boolean;
  leftIcon?: ReactNode;
};

const VARIANT_CLASSES: Record<Variant, string> = {
  primary:
    "bg-noturno-orange text-noturno-black hover:bg-noturno-orange-dark " +
    "shadow-[0_8px_24px_-8px_rgba(255,182,33,0.55)]",
  ghost:
    "bg-transparent text-noturno-grey-light-clean border border-white/10 " +
    "hover:border-noturno-orange/50 hover:text-white",
};

export function BaseButton({
  variant = "primary",
  loading = false,
  leftIcon,
  children,
  disabled,
  className = "",
  ...props
}: BaseButtonProps) {
  const isDisabled = disabled || loading;
  return (
    <button
      {...props}
      disabled={isDisabled}
      aria-busy={loading}
      className={
        "inline-flex h-12 w-full items-center justify-center gap-2 rounded-xl px-5 " +
        "text-sm font-semibold tracking-wide transition-all duration-200 " +
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-noturno-orange/60 " +
        "disabled:cursor-not-allowed disabled:opacity-60 " +
        VARIANT_CLASSES[variant] +
        " " +
        className
      }
    >
      {loading ? (
        <span className="size-4 animate-spin rounded-full border-2 border-current border-t-transparent" />
      ) : (
        leftIcon
      )}
      {children}
    </button>
  );
}
